- hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      yum:
        name:
          - git
          - gcc
          - libffi-devel
          - python3
          - python3-pip
          - python3-virtualenv
          - nginx
        state: present

    
    - name: Remove any existing Docker installation
      yum:
        name: docker
        state: absent
      ignore_errors: yes

    - name: Install Docker latest version
      shell: |
        sudo tee /etc/yum.repos.d/docker.repo <<EOF
        [docker]
        name=Docker
        baseurl=https://download.docker.com/linux/centos/7/x86_64/stable
        enabled=1
        gpgcheck=1
        gpgkey=https://download.docker.com/linux/centos/gpg
        EOF
        sudo yum update -y
        sudo yum install -y docker-ce docker-ce-cli containerd.io


    - name: Install Docker Compose 2.19.0
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Clone Sentry self-hosted repository
      git:
        repo: 'https://github.com/getsentry/self-hosted.git'
        dest: /opt/sentry

    - name: Change directory ownership
      file:
        path: /opt/sentry
        owner: ec2-user
        group: ec2-user
        state: directory
        recurse: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Check if Docker is installed and accessible
      command: docker --version
      ignore_errors: yes
      register: docker_check

    - name: Run install script for Sentry if Docker is installed and accessible
      shell: ./install.sh
      args:
        chdir: /opt/sentry
      when: docker_check.rc == 0

    - name: Start Sentry
      shell: |
        cd /opt/sentry
        docker-compose up -d
      args:
        chdir: /opt/sentry

    - name: Ensure Sentry is running
      command: docker-compose ps
      args:
        chdir: /opt/sentry
      register: docker_ps

    - debug:
        var: docker_ps.stdout_lines
